repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.941
    hooks:
      - id: mypy
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        description: Python style guide enforcement
        entry: flake8
        args: [ "--config=setup.cfg" ]
        language: python
        types: [ python ]
